language: PHP

php:
  - '5.5'
  - '7.0'
  - '7.1'

install:
  - sudo apt-get install -qq --force-yes beanstalkd
  - sudo apt-get install --force-yes redis-server
  - pecl install swoole
  - composer install

script:
  - vendor/bin/phpunit
